name: test

permissions:
  contents: write

on:
  push:
    tags:
      - "*"

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            index.js
      - uses: ./
  test2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            README.md
            LICENSE
      - uses: ./
